name: "Lesson 3 - Exercise 1"

on:
  workflow_dispatch:

jobs:
  reuse-workflow:
    uses: tamayojohnaaron/microservices-workflows/.github/workflows/lesson3_exercise1.yaml@main
    with:
      actor: ${{ github.actor }}
